const data = {
    products: [
        {
            _id: '1',
            name: 'regular use formal',
            category: 'shirts',
            image: '/images/p1.jpg',
            countInStock: 10,
            price: 500,
            brand: 'femina',
            rating: 4.5,
            numReviews: 10,
            descrption: 'high quality product',
        },
        {
            _id: '2',
            name: 'Cream color handbag',
            category: 'shirts',
            image: '/images/p1.jpg',
            countInStock: 0,
            price: 500,
            brand: 'nike',
            rating: 4.0,
            numReviews: 10,
            descrption: 'high quality product',
        },
        {
            _id: '3',
            name: 'party wear long gown',
            category: 'shirts',
            image: '/images/p1.jpg',
            countInStock: 12,
            price: 500,
            brand: 'femina',
            rating: 4.5,
            numReviews: 10,
            descrption: 'high quality product',
        },
        {
            _id: '4',
            name: 'party wear long gown',
            category: 'shirts',
            image: '/images/p1.jpg',
            countInStock: 5,
            price: 500,
            brand: 'femina',
            rating: 4.5,
            numReviews: 10,
            descrption: 'high quality product',
        },
        {
            _id: '5',
            name: 'party wear long gown',
            category: 'shirts',
            image: '/images/p1.jpg',
            countInStock: 15,
            price: 500,
            brand: 'femina',
            rating: 4.5,
            numReviews: 10,
            descrption: 'high quality product',
        },
        {
            _id: '6',
            name: 'party wear long gown',
            category: 'shirts',
            image: '/images/p1.jpg',
            countInStock: 20,
            price: 500,
            brand: 'femina',
            rating: 4.5,
            numReviews: 10,
            descrption: 'high quality product',
        }
    ]
}
export default data;